"""Deterministic reduced-briefing pipeline."""

from chief_of_staff.pipeline.briefing import (
    BriefingContentKind,
    BriefingItem,
    BriefingPlan,
    BriefingSection,
    BriefingSectionName,
    BriefingValidationError,
    CalendarEventClassification,
    ChiefOfStaffNoteInputs,
    ConflictClaim,
    PlanConflict,
    PriorityInputs,
    RenderedBriefing,
    SourceLink,
    SuppressedDuplicate,
    TaskCandidateAudit,
    TaskPlanningConfidence,
    build_reduced_plan,
    classify_calendar_event,
    render_briefing,
    validate_briefing,
)
from chief_of_staff.pipeline.context import (
    InvocationContext,
    WorkdayType,
    reconcile_calendar_workday_context,
    resolve_context,
)
from chief_of_staff.pipeline.deduplication import (
    CrossSourceAssociation,
    DeduplicationResult,
    RecordCluster,
    deduplicate_records,
)
from chief_of_staff.pipeline.normalization import (
    AssociatedSourceFacts,
    NormalizedRecord,
    Provenance,
    RecordKind,
    normalize_item,
)
from chief_of_staff.pipeline.ranking import (
    FactorSource,
    PriorityBand,
    RankedCandidate,
    RankingFactor,
    RankingFactorKind,
    RankingResult,
    SuppressedCandidate,
    rank_candidates,
)
from chief_of_staff.pipeline.runner import (
    DeterministicBriefingPipeline,
    PipelineResult,
    recompose_pipeline_result,
)

__all__ = (
    "AssociatedSourceFacts",
    "BriefingContentKind",
    "BriefingItem",
    "BriefingPlan",
    "BriefingSection",
    "BriefingSectionName",
    "BriefingValidationError",
    "CalendarEventClassification",
    "ChiefOfStaffNoteInputs",
    "ConflictClaim",
    "CrossSourceAssociation",
    "DeduplicationResult",
    "DeterministicBriefingPipeline",
    "FactorSource",
    "InvocationContext",
    "NormalizedRecord",
    "PipelineResult",
    "PlanConflict",
    "PriorityBand",
    "PriorityInputs",
    "Provenance",
    "RankedCandidate",
    "RankingFactor",
    "RankingFactorKind",
    "RankingResult",
    "RecordCluster",
    "RecordKind",
    "RenderedBriefing",
    "SourceLink",
    "SuppressedCandidate",
    "SuppressedDuplicate",
    "TaskCandidateAudit",
    "TaskPlanningConfidence",
    "WorkdayType",
    "build_reduced_plan",
    "classify_calendar_event",
    "deduplicate_records",
    "normalize_item",
    "rank_candidates",
    "recompose_pipeline_result",
    "reconcile_calendar_workday_context",
    "render_briefing",
    "resolve_context",
    "validate_briefing",
)
